version: '3.8'

services:
  postgres:
    image: postgres:11
    container_name: postgres_olist
    environment:
      POSTGRES_DB: olist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
